#!/bin/bash
# r2-checks.sh — one mechanical check per verifiable finding of the 2026-09-16
# comprehensive review (R2-nn), against the current tree, printed as
#   ID   expectation-in-words   observed
# so the disposition table in reviews/ can cite what was actually looked at.
# GOOD and NOTE findings have no check (nothing to fix). Read-only.
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 2
c() { grep -cE "$2" "$1" 2>/dev/null || echo 0; }          # count matches in file
n() { grep -rlE "$2" $1 2>/dev/null | wc -l; }              # files matching in dir
say() { printf '%-7s %-58s %s\n' "$1" "$2" "$3"; }

say R2-02  "branch-status refuses on shallow clone"           "is-shallow: $(c devtools/branch-status is-shallow-repository)"
say R2-03  "register rows for 08-23T2340Z and 09-13 reports"  "$(c reviews/README.md '2026-08-23T2340Z-ex032') / $(c reviews/README.md '2026-09-13-foundation')"
say R2-04  "README 'kept current' sentence gone"              "$(c README.md 'kept current')"
say R2-05  "README 'no longer re-derivable' gone"             "$(c README.md 'no longer re-derivable')"
say R2-06  "'then silence' gone from README/docs (not §5)"    "README $(c README.md 'then silence') docs $(n docs 'then silence')"
say R2-07  "README names alt 1 / len 27 / sysfs"              "alt $(c README.md 'alt(ernate)? ?(setting )?1') mtu9 $(c README.md 'mtu 9|9-byte') sysfs $(c README.md sysfs)"
say R2-08  "README 'ten documents' gone; links tooling-index" "ten $(c README.md 'ten documents') idx $(c README.md 'tooling-index')"
say R2-09  "README: --tools-only before --apply"              "first-mention lines: tools-only $(grep -n -m1 -- '--tools-only' README.md | cut -d: -f1) apply $(grep -n -m1 -- '--apply' README.md | cut -d: -f1)"
say R2-10  "README header specific (transparent/alt)"         "$(sed -n 1,6p README.md | grep -ciE 'alt|transparent|mSBC')"
say R2-12  "BRIEF §9 names CI red thread"                     "$(c BRIEF.md 'CI was red')"
say R2-13  "BRIEF header has no tip hash"                     "tip-word $(sed -n 1,20p BRIEF.md | grep -c 'tip `')"
say R2-15  "plan no longer says denominator not re-derivable" "$(c docs/investigation-plan.md 're-derive')"
say R2-16  "HISTORY SUPERSEDED forward pointers"              "$(c HISTORY.md 'SUPERSEDED')"
say R2-17  "HISTORY current-state heading points to BRIEF"    "$(grep -n 'Current state' HISTORY.md | head -2 | tr '\n' ' ')"
say R2-20  "tooling-index prompt section (kept by decision?)" "$(c docs/tooling-index.md 'so they do not prompt')"
say R2-21  "issues.md BT-1 cites EX-03x/04x"                  "$(c docs/issues.md 'EX-03[3-9]|EX-04[0-9]')"
say R2-22  "issues.md has BlueZ crash entries"                "$(c docs/issues.md 'patches/bluez|0001|0002')"
say R2-23  "issues.md BT-4 backtrace status current"          "$(c docs/issues.md 'Still needed before filing')"
say R2-25  "bug-report timing 7.6–16.2 gone"                  "$(c docs/bug-report.md '7\.6.16\.2|155\.8')"
say R2-26  "bug-report Regression: No gone; kernel list"      "regno $(c docs/bug-report.md 'Regression: No') k31 $(c docs/bug-report.md '7\.0\.0-31')"
say R2-27  "bug-report 'Workaround in use' gone"              "$(c docs/bug-report.md 'Workaround in use')"
say R2-29  "fix-proposal has a revision/superseded banner"    "$(c docs/fix-proposal.md 'SUPERSEDED|superseded|Revision|revision')"
say R2-30  "fix-proposal '~53 s' fossil"                      "$(c docs/fix-proposal.md '53 s')"
say R2-31  "fix-proposal §8 stale rows (2026-08-11)"          "$(c docs/fix-proposal.md 'as of 2026-08-11')"
say R2-33  "source-map derives seen? incl. bt-snapshot"       "$(c docs/source-map.md 'bt-snapshot')"
say R2-34  "source-map/access kernel table by date not index" "-30 $(c docs/source-map.md '7\.0\.0-30') -31 $(c docs/source-map.md '7\.0\.0-31')"
say R2-35  "external brief carries sysfs alt-1 observation"   "sysfs $(c docs/external-review-brief.md sysfs) EX-043 $(c docs/external-review-brief.md 'EX-04')"
say R2-38  "plan revision: '13 of 34' withdrawn text; silence" "$(c docs/investigation-plan.md '13 of 34') / $(c docs/investigation-plan.md 'silence')"
say R2-39  "plan backlog has status column / BL-09 done"      "status $(c docs/investigation-plan.md 'status') BL-09 $(grep -n 'BL-09' docs/investigation-plan.md | head -1 | cut -c1-80)"
say R2-40  "plan/report name the v5.12 commit"                "plan $(c docs/investigation-plan.md 517b693351a2) report $(c docs/bug-report.md 517b693351a2)"
say R2-42  "firmware-hypothesis points to alt-1 finding"      "$(c docs/firmware-hypothesis.md 'alt')"
say R2-43  "changes-applied covers patched bluetoothd"        "$(c docs/changes-applied.md 'bluetoothd|/usr/local|drop-in') restore $(c docs/restore-original-state.md 'drop-in|patched')"
say R2-45  "restore guide: user-wide tool setting and rm -rf repo" "$(c docs/restore-original-state.md 'attribution') / $(c docs/restore-original-state.md 'rm -rf')"
say R2-46  "checklist has BlueZ patches + regression gate"    "$(c docs/pre-submission-checklist.md 'patches/bluez|0001') / $(c docs/pre-submission-checklist.md '517b|regression')"
say R2-48  "tools not named in tooling-index"                 "$(for t in tools/bt-* tools/*.sh devtools/*; do b=$(basename "$t"); grep -q "$b" docs/tooling-index.md || printf '%s ' "$b"; done)"
say R2-49  "bt-hang-watchdog header warns (destroy/never arm)" "$(c bin/bt-hang-watchdog 'destroy|EX-023|never arm|do not arm')"
say R2-50  "watchdog header 'NEVER been observed' claim"      "$(c bin/bt-hang-watchdog 'NEVER been observed')"
say R2-51  "bt-trace/bt-usbmon sub-second filenames"          "trace $(c bin/bt-trace '%N|nanos|%s') usbmon $(c bin/bt-usbmon '%N|nanos|%s')"
say R2-52  "bt-trace disk_guard loop guarded"                 "$(grep -n 'free_gb' bin/bt-trace | tr '\n' ' ' | cut -c1-120)"
say R2-54  "bt-trial-auto: ExecStop autostop / TimeoutStopSec" "$(grep -E 'ExecStop|TimeoutStopSec' systemd/bt-trial-auto.service | tr '\n' ' ')"
say R2-55  "modprobe/dyndbg names the len27 site"             "$(c etc/modprobe.d/btusb-qca9377.conf 'len 27|mtu 9|alt') / $(n tools 'len 27 mtu 9')"
say R2-56  "bt-usbmon.service BUS=3 baked in"                 "$(c systemd/bt-usbmon.service 'BT_USBMON_BUS=3')"
say R2-59  "install.sh stamp under tools-only"                "$(grep -n 'installed-at' install.sh | head -3 | cut -c1-80 | tr '\n' ' ')"
say R2-60  "install.sh run() comment vs case arm"             "$(grep -n 'install|rm|rmdir' install.sh | head -2 | cut -c1-90 | tr '\n' ' ')"
say R2-61  "install.sh --help range"                          "$(grep -n "sed -n '2,1" install.sh | head -1 | cut -c1-60) hdr16: $(sed -n 16p install.sh | cut -c1-50)"
say R2-62  "install.sh installs crash/fault-window/usbstate/guards" "$(c install.sh 'bt-crash') $(c install.sh 'bt-fault-window') $(c install.sh 'bt-usbstate') $(c install.sh 'bt-guards')"
say R2-64  "bt-trial abort checks git ls-files"               "$(c tools/bt-trial 'ls-files')"
say R2-65  "bt-trial autostop probes hci_alive"               "$(grep -n 'hci_alive' tools/bt-trial | head -3 | cut -c1-80 | tr '\n' ' ')"
say R2-66  "bt-snapshot hardcodes 3-3"                        "$(c tools/bt-snapshot '3-3')"
say R2-67  "bt-archive --check counts AMBIGUOUS"              "$(grep -n 'AMBIGUOUS' tools/bt-archive | head -4 | cut -c1-70 | tr '\n' ' ')"
say R2-70  "sanitize-logs keeps SIG base UUIDs"               "$(c tools/sanitize-logs.sh '00805f9b34fb')"
say R2-71  "bt-capdiff --since intersects"                    "$(grep -n 'SINCE\|UNTIL' tools/bt-capdiff | grep -E 'lo=|hi=' | head -2 | cut -c1-80 | tr '\n' ' ')"
say R2-72  "bt-postmortem verdict text"                       "late $(c tools/bt-postmortem 'too late') alt $(c tools/bt-postmortem 'alt')"
say R2-73  "bt-health-report mode-aware"                      "$(c tools/bt-health-report.sh 'bt-mode|experiment')"
say R2-74  "bt-exhibit hardcodes 13d3:3503; bt-actions PROF"  "$(c tools/bt-exhibit '13d3:3503') / $(c tools/bt-actions 'PROF')"
say R2-76  "bt-status \\bsco\\b"                                "$(c tools/bt-status '\\\\bsco\\\\b|\\\\bSCO\\\\b')"
say R2-77  "bt-incident records sanitiser outcome"            "$(grep -n 'sanitised' tools/bt-incident | head -3 | cut -c1-80 | tr '\n' ' ')"
say R2-78  "bt-diagnose probe opt-in"                         "$(c tools/bt-diagnose -- '--probe')"
say R2-79  "bt-status cites fix-proposal §3a; verify-restored dated constants" "$(c tools/bt-status 'fix-proposal') / $(c tools/verify-restored.sh '2026-08-10') / $(c tools/verify-restored.sh 'settings.json')"
say R2-81  "bt-verify-install CONFLICT + tools-only advice"   "conflict $(c tools/bt-verify-install 'CONFLICT') advice $(grep -n -- '--apply\|--tools-only' tools/bt-verify-install | head -3 | cut -c1-70 | tr '\n' ' ')"
say R2-82  "bt-verify-kernel-mechanism strings fallback"      "$(c tools/bt-verify-kernel-mechanism 'command -v strings|od ')"
say R2-84  "bt-sco retracted signature line; --window in usage" "sig $(c tools/bt-sco 'unanswered synchronous') usage $(sed -n 2,26p tools/bt-sco | grep -c -- '--window')"
say R2-85  "bt-window header exit contract; lsusb"            "$(c tools/bt-window 'untreated and still running') lsusb $(c tools/bt-window lsusb)"
say R2-86  "bt-fault-window --at keeps zone"                  "$(grep -n 'date -d' tools/bt-fault-window | head -2 | cut -c1-90 | tr '\n' ' ')"
say R2-88  "bt-usbstate resolves by VID/PID"                  "$(c tools/bt-usbstate 'idVendor|BT_VID')"
say R2-91  "bt-context redaction covers lower/underscore"     "$(grep -n '0-9A-F' tools/bt-context | head -2 | cut -c1-90 | tr '\n' ' ')"
say R2-92  "bt-guards through the journal seam"               "direct $(c tools/bt-guards 'journalctl') seam $(c tools/bt-guards 'bt_journal')"
say R2-94  "bt-state probe opt-in; bt-incident uses usbstate" "$(c tools/bt-state -- '--probe') / $(c tools/bt-incident 'bt-usbstate')"
say R2-97  "journal.sh fixture parser handles several -u"     "$(grep -n -- '-u)' tools/lib/journal.sh | head -2 | cut -c1-80 | tr '\n' ' ')"
say R2-98  "iso_secs handles Z"                               "$(grep -n 'iso_secs' tools/lib/evidence-window.sh | head -1 | cut -c1-60) Z: $(grep -A12 'iso_secs()' tools/lib/evidence-window.sh | grep -c "Z")"
say R2-101 "pinning tests commented (BL-03/BL-08)"            "$(grep -c 'BL-03\|BL-08' tests/run-tests)"
say R2-102 "tools-only .disabled test exists"                 "$(c tests/run-tests 'tools-only leaves')"
say R2-103 "tests/README ~2 s and fixtures rows"              "2s $(c tests/README.md '~2 s') red-note $(c tests/README.md 'red|FAILED')"
say R2-106 "devtools/status remedy honours mode"              "$(grep -n -- '--apply\|--tools-only' devtools/status | head -4 | cut -c1-80 | tr '\n' ' ')"
say R2-107 "devtools/README lists every script"               "missing: $(for t in devtools/*; do b=$(basename "$t"); [[ $b == README.md ]] && continue; grep -q "$b" devtools/README.md || printf '%s ' "$b"; done)"
say R2-109 "(=R2-02)"                                          "see R2-02"
say R2-111 "instruments agree on red run"                     "cov $(c devtools/coverage 'red run|failing run') awk $(c devtools/awk-coverage 'red run|failing run|FAILED') tc $(c devtools/test-comprehension 'red run|failing run|cannot measure')"
say R2-114 "exhibit index claims untruncated"                 "cut-rows $(grep -c ' |$' evidence/exhibits/README.md) RS $(c tools/bt-exhibit 'RS=')"
say R2-115 "evidence/README names exhibits/ + alt-1"          "$(c evidence/README.md 'exhibits/') / $(c evidence/README.md 'alt')"
say R2-117 "patches README has firing line"                   "$(c patches/bluez/README.md 'fired four times')"
say R2-119 "verify.sh covers rows beyond UT"                  "ids $(grep -oE '\b(UT|CS|TC|HC|TX|SE|CR|FD|R2|TP)-[0-9]+' reviews/verify.sh | sort -u | wc -l) of $(grep -cE '^\| [A-Z][A-Z0-9]?-[0-9]+' reviews/README.md)"
say R2-120 "reviews/README names verify.sh scope"             "$(c reviews/README.md 'verify.sh')"
